name: Kingdominstruction
favicon: null
layout_spectrum: 0.9923921735025942
typography_spectrum: 0.863190796924755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.583259396487847
  lightness: 0.27019993611611426
  saturation: 0.6388893746770918
  rhythmicContrast: 0.17986702639609575
purpose: []
